name: Deploy to Preview Channel

on: pull_request

jobs:
    build_and_preview:
        if: "!contains(github.event.head_commit.message, '[skip-ci]')"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Retrieve npm cache (if any)
              uses: actions/cache@v2.1.6
              with:
                  path: ~/.npm
                  key: npm-packages

            - name: Install Dependencies
              run: npm install

            - name: Build files
              run: npm run build

            - name: Deploy to Firebase
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                repoToken: '${{ secrets.GITHUB_TOKEN }}'
                firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOVIE_RECOMMENDATION_77E17 }}'
                projectId: movie-recommendation-77e17
              env:
                  FIREBASE_CLI_PREVIEWS: hostingchannels
