name: Deploy Preview

on:
    workflow_run:
        workflows:
            - Build Preview
        types:
            - completed

jobs:
    deploy_preview:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                workflow: build-preview.yml
                pr: ${{github.event.pull_request.number}}
                name: dist
            - name: Deploy to Firebase
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                repoToken: '${{ secrets.GITHUB_TOKEN }}'
                firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOVIE_RECOMMENDATION_77E17 }}'
                projectId: movie-recommendation-77e17
              env:
                  FIREBASE_CLI_PREVIEWS: hostingchannels
