name: Deploy to Prod

on:
    push:
        branches:
            - release
jobs:
    deploy_prod_website:
        if: "!contains(github.event.head_commit.message, '[skip-ci]')"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v3

            - name: Retrieve npm cache (if any)
              uses: actions/cache@v2.1.7
              with:
                  path: ~/.npm
                  key: npm-packages

            - name: Install Dependencies
              run: npm install

            - name: Build files
              run: npm run build

            - name: Deploy to Firebase
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOVIE_RECOMMENDATION_77E17 }}'
                  channelId: live
                  target: prod
              env:
                  FIREBASE_CLI_PREVIEWS: hostingchannels

            - name: Comment on PR
              uses: actions/github-script@v6
              env:
                  MERGE_COMMIT_MESSAGE: '${{ github.event.head_commit.message }}'
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                    const [_, prNumber] = process.env.MERGE_COMMIT_MESSAGE.match(/#([\d]+)/) || [];
                    if(prNumber) {
                        github.rest.issues.createComment({
                            body: '🚀 Successfully deployed to [https://movie-recommendation.shashanks.ga](https://movie-recommendation.shashanks.ga).',
                            issue_number: prNumber,
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                        });
                    }
