name: Deploy to Preview Channel

on: pull_request

jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2
            - name: Install Dependencies
              run: npm install
            - name: Run style check
              run: npm run lint
            - name: Build files
              run: npm run build
            - name: Deploy to Firebase
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
                  projectId: movie-recommendation-77e17
              env:
                  FIREBASE_CLI_PREVIEWS: hostingchannels
