name: Deploy to Dev

on:
    push:
        branches:
            - test-branch
jobs:
    deploy_dev_website:
        if: "!contains(github.event.head_commit.message, '[skip-ci]')"
        runs-on: ubuntu-latest
        steps:
            - name: Comment on PR
              uses: actions/github-script@v3
              env:
               MERGE_COMMIT_MESSAGE: '${{ github.event.head_commit.message }}'
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                    const [_, prNumber] = process.env.MERGE_COMMIT_MESSAGE.match(/#([\d]+)/) || [];
                    if(prNumber) {
                        github.issues.createComment({
                            body: '🚀 Successfully deployed to: [https://movie-recommendation-dev.shashanks.ga](https://movie-recommendation-dev.shashanks.ga)',
                            issue_number: prNumber,
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                        });
                    }
