name: Deploy to Dev

on:
    push:
        branches:
            - master
jobs:
    deploy_dev_website:
        if: "!contains(github.event.head_commit.message, '[skip-ci]')"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Retrieve npm cache (if any)
              uses: actions/cache@v2.1.6
              with:
                  path: ~/.npm
                  key: npm-packages

            - name: Install Dependencies
              run: npm install

            - name: Build files
              run: npm run build

            - name: Deploy to Firebase
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOVIE_RECOMMENDATION_77E17 }}'
                  channelId: live
                  target: dev
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

            - name: Comment on PR
              uses: actions/github-script@v4.0.2
              env:
                  MERGE_COMMIT_MESSAGE: '${{ github.event.head_commit.message }}'
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                    const [_, prNumber] = process.env.MERGE_COMMIT_MESSAGE.match(/#([\d]+)/) || [];
                    if(prNumber) {
                        github.issues.createComment({
                            body: '🚀 Successfully deployed to [https://movie-recommendation-dev.shashanks.ga](https://movie-recommendation-dev.shashanks.ga)',
                            issue_number: prNumber,
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                        });
                    }
